import {createInspectionPin,bindInspectionClick} from '../terrain/inspection-pin.js';
import {entityStyle,entityColor} from '../terrain/feature-style.js';
import {MapCamera,detailAtScale,detailName} from '../terrain/map-camera.js';
import {DetailTiles} from '../terrain/detail-tiles.js';
import {makeDetailPalette,tileImage,drawDetailFeatures} from '../terrain/detail-render.js';
import {reliefShades} from '../terrain/relief.js';

export function createBuilderMap(container,solver,callbacks){
 const canvas=document.createElement('canvas');canvas.className='builder-canvas';canvas.tabIndex=0;canvas.setAttribute('aria-label','World Builder map. Scroll to zoom, drag to pan.');container.append(canvas);
 const extent=solver.historicalMap?.bounds||{x:0,y:0,width:solver.W-1,height:solver.H-1};
 const pin=createInspectionPin(container);let inspection=null;
 const ctx=canvas.getContext('2d'),camera=new MapCamera(),abort=new AbortController();let width=0,height=0,frame=0,disposed=false,entities=[],options={tool:'select',radius:2,layer:'terrain',layers:[]},selection=null,drag=null,ghost=null,draft=[],images=new WeakMap(),palette=null,lastLayer='',lastClimateRevision=null,viewportTimer=0;
 const tiles=solver.environment?new DetailTiles(solver,()=>queue()):null;
 const overview=document.createElement('canvas');overview.width=solver.W;overview.height=solver.H;const oc=overview.getContext('2d'),picture=oc.createImageData(solver.W,solver.H),shades=solver.environment?reliefShades(solver.environment,solver.W,solver.H):null;
 const overviewPalette=solver.environment?makeDetailPalette(solver):null;
 for(let i=0;i<solver.N;i++){let c=solver.config.types[solver.typeAt(i)]?.color||'#627565';if(!/^#[0-9a-f]{6}$/i.test(c))c='#627565';for(let k=0;k<3;k++)picture.data[i*4+k]=Math.min(255,(overviewPalette?.[i][k]??parseInt(c.slice(1+k*2,3+k*2),16))*(shades?.[i]||1));picture.data[i*4+3]=255;}oc.putImageData(picture,0,0);
 function listen(target,event,fn,extra={}){target.addEventListener(event,fn,{...extra,signal:abort.signal});}
 function queue(){if(!frame&&!disposed)frame=requestAnimationFrame(render);}
 function changed(){queue();clearTimeout(viewportTimer);viewportTimer=setTimeout(()=>{callbacks.viewport({...camera.bounds(width,height),detail:detailAtScale(camera.scale)});callbacks.camera(state());},120);}
 function state(){return {center:camera.point(width/2,height/2),scale:camera.scale};}
 function fit(){if(!width||!height)return;camera.fit(width,height,extent.width,extent.height);camera.x-=extent.x*camera.scale;camera.y-=extent.y*camera.scale;changed();}
 function resize(){const w=container.clientWidth,h=container.clientHeight;if(!w||!h)return;const center=camera.point(width/2,height/2),first=!width;width=w;height=h;const ratio=Math.min(2,devicePixelRatio||1);canvas.width=width*ratio;canvas.height=height*ratio;if(first)fit();else{camera.minimum=Math.min(width/extent.width,height/extent.height);camera.x=width/2-center.x*camera.scale;camera.y=height/2-center.y*camera.scale;changed();}}
 const observer=new ResizeObserver(resize);observer.observe(container);resize();
 const local=e=>{const r=canvas.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};};
 const world=e=>{const p=local(e);return camera.point(p.x,p.y);};const inside=p=>p.x>=extent.x&&p.y>=extent.y&&p.x<=extent.x+extent.width&&p.y<=extent.y+extent.height;
 const screen=p=>[camera.x+p[0]*camera.scale,camera.y+p[1]*camera.scale];
 function distance(p,a,b){const dx=b[0]-a[0],dy=b[1]-a[1],t=Math.max(0,Math.min(1,((p.x-a[0])*dx+(p.y-a[1])*dy)/(dx*dx+dy*dy||1)));return Math.hypot(p.x-a[0]-dx*t,p.y-a[1]-dy*t);}
 function vertexAt(p){if(!selection||selection.geometry==='point'||options.layers.find(l=>l.id===selection.layer)?.locked)return -1;return selection.points.findIndex(v=>Math.hypot(p.x-v[0],p.y-v[1])<9/camera.scale);}
 function hit(p){for(const e of [...entities].reverse().sort((a,b)=>(a.geometry==='polygon')-(b.geometry==='polygon'))){if(e.geometry==='point'){if(Math.hypot(p.x-e.points[0][0],p.y-e.points[0][1])<10/camera.scale)return e;}else{if(e.geometry==='polygon'){let inside=false;for(let i=0,j=e.points.length-1;i<e.points.length;j=i++){const a=e.points[i],b=e.points[j];if((a[1]>p.y)!==(b[1]>p.y)&&p.x<(b[0]-a[0])*(p.y-a[1])/(b[1]-a[1])+a[0])inside=!inside;}if(inside)return e;}for(let i=1;i<e.points.length;i++)if(distance(p,e.points[i-1],e.points[i])<8/camera.scale)return e;}}return null;}
 function sample(p){if(!tiles)return null;for(let l=8;l>=0;l--){const span=32/2**l,t=tiles.cache.get(`${l}/${Math.floor(p.x/span)}/${Math.floor(p.y/span)}`);if(!t)continue;const x=Math.max(0,Math.min(32,Math.round((p.x-t.x*span)/t.step))),y=Math.max(0,Math.min(32,Math.round((p.y-t.y*span)/t.step)));return t.points[y*33+x];}return null;}
 bindInspectionClick(canvas,()=>['select','pan'].includes(options.tool),e=>{const p=world(e);return inside(p)?p:null;},p=>callbacks.inspect?.(p),abort.signal);
 listen(canvas,'wheel',e=>{e.preventDefault();const p=local(e);camera.zoomAt(p.x,p.y,Math.exp(-e.deltaY*.0015));changed();},{passive:false});
 listen(canvas,'contextmenu',e=>e.preventDefault());
 listen(canvas,'pointerdown',e=>{canvas.focus();canvas.setPointerCapture(e.pointerId);const p=world(e);if(options.tool==='select'&&e.button===0){const vertex=vertexAt(p);if(vertex>=0){drag={type:'vertex',vertex,start:p,screen:local(e),entity:selection,moved:false};return;}selection=hit(p);callbacks.select(selection);drag={type:selection&&!options.layers.find(l=>l.id===selection.layer)?.locked?'entity':'pan',start:p,screen:local(e),last:local(e),entity:selection,moved:false};}else if(options.tool==='pan'||e.button!==0)drag={type:'pan',last:local(e),screen:local(e),moved:false};else drag={type:'tool',start:p,screen:local(e),moved:false};queue();});
 listen(canvas,'pointermove',e=>{const p=world(e);ghost=p;if(drag){const now=local(e);drag.moved ||=Math.hypot(now.x-drag.screen.x,now.y-drag.screen.y)>4;if(drag.type==='pan'){camera.x+=now.x-drag.last.x;camera.y+=now.y-drag.last.y;drag.last=now;changed();}else if(drag.type==='entity'||drag.type==='vertex'){drag.delta=[p.x-drag.start.x,p.y-drag.start.y];queue();}}else queue();const s=sample(p);callbacks.hover(inside(p)?{...p,...s}:null);});
 listen(canvas,'pointerleave',()=>{ghost=null;queue();});
 listen(canvas,'pointerup',e=>{const p=world(e),d=drag;drag=null;if(!d)return;if(d.type==='vertex'&&d.moved&&d.delta){callbacks.move({...d.entity,points:d.entity.points.map((v,i)=>i===d.vertex?[v[0]+d.delta[0],v[1]+d.delta[1]]:v)});}else if(d.type==='entity'&&d.moved&&d.delta){callbacks.move({...d.entity,points:d.entity.points.map(v=>[v[0]+d.delta[0],v[1]+d.delta[1]])});}else if(d.type==='tool'&&!d.moved&&inside(p)){if(['line','polygon','river'].includes(options.tool)){if(!draft.length||Math.hypot(draft.at(-1)[0]-p.x,draft.at(-1)[1]-p.y)>.001)draft.push([p.x,p.y]);callbacks.draft(draft.length);}else if(options.tool==='point')callbacks.place([[p.x,p.y]],'point');else callbacks.modify(options.tool,p,[],sample(p));}changed();});
 listen(canvas,'pointercancel',()=>{drag=null;queue();});
 function finish(){const tool=options.tool,n=tool==='polygon'?3:2;if(draft.length<n)return;const points=draft;draft=[];callbacks.draft(0);if(tool==='river')callbacks.modify('river',{x:points[0][0],y:points[0][1]},points,sample({x:points[0][0],y:points[0][1]}));else callbacks.place(points,tool);queue();}
 listen(canvas,'dblclick',finish);listen(canvas,'keydown',e=>{if(e.key==='Escape'){draft=[];callbacks.draft(0);queue();}else if(e.key==='Enter'){e.preventDefault();finish();}else if(['+','=','-','0'].includes(e.key)){e.preventDefault();if(e.key==='0')fit();else{camera.zoomAt(width/2,height/2,e.key==='-'?.5:2);changed();}}});
 function drawEntity(e){let points=e.points;if(drag?.type==='vertex'&&drag.entity.id===e.id&&drag.delta)points=points.map((p,i)=>i===drag.vertex?[p[0]+drag.delta[0],p[1]+drag.delta[1]]:p);if(drag?.type==='entity'&&drag.entity.id===e.id&&drag.delta)points=points.map(p=>[p[0]+drag.delta[0],p[1]+drag.delta[1]]);const path=points.map(screen);ctx.strokeStyle=entityColor(e,e.id===selection?.id);ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=entityStyle.lineWidth;ctx.beginPath();if(e.geometry==='point'){const [x,y]=path[0];ctx.arc(x,y,entityStyle.pointSize/2,0,Math.PI*2);ctx.fill();}else{path.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));if(e.geometry==='polygon'){ctx.closePath();}ctx.stroke();if(e.id===selection?.id&&options.tool==='select'){for(const [x,y] of path){ctx.fillStyle='#f6ca7c';ctx.fillRect(x-3,y-3,6,6);}}}if(camera.scale>12||e.id===selection?.id){ctx.font='12px system-ui';ctx.fillStyle='#eff3ee';ctx.shadowColor='#111';ctx.shadowBlur=4;ctx.fillText(e.name,path[0][0]+9,path[0][1]-8);ctx.shadowBlur=0;}}
 function render(){frame=0;if(!width||!height||!container.clientWidth||!container.clientHeight)return;ctx.setTransform(canvas.width/width,0,0,canvas.height/height,0,0);ctx.clearRect(0,0,width,height);ctx.fillStyle='#0e171b';ctx.fillRect(0,0,width,height);const bounds=camera.bounds(width,height);let visible=[];ctx.save();ctx.beginPath();ctx.rect(camera.x+extent.x*camera.scale,camera.y+extent.y*camera.scale,extent.width*camera.scale,extent.height*camera.scale);ctx.clip();
  if(options.layers.find(l=>l.id==='terrain')?.visible!==false){ctx.imageSmoothingEnabled=options.layer!=='terrain';ctx.drawImage(overview,camera.x,camera.y,(solver.W-1)*camera.scale,(solver.H-1)*camera.scale);if(tiles){if(lastLayer!==options.layer||lastClimateRevision!==solver.climateRevision){lastLayer=options.layer;lastClimateRevision=solver.climateRevision;palette=makeDetailPalette(solver,options.layer);images=new WeakMap();}visible=tiles.request(bounds,camera.scale);for(const item of visible){const {tile,alpha}=item,morph=Math.round(alpha*64)/64;let cached=images.get(tile);if(!cached||cached.morph!==morph){cached={morph,image:tileImage(tile,solver,palette,options.layer,morph)};images.set(tile,cached);}ctx.globalAlpha=options.layer==='terrain'||tile.level===0?1:alpha;const span=32*tile.step;ctx.drawImage(cached.image,.5,.5,cached.image.width-1,cached.image.height-1,camera.x+tile.x*span*camera.scale,camera.y+tile.y*span*camera.scale,span*camera.scale,span*camera.scale);}ctx.globalAlpha=1;if(options.layers.find(l=>l.id==='natural-features')?.visible!==false)drawDetailFeatures(ctx,visible,camera,detailAtScale(camera.scale),options.layer);}}
  for(const entity of entities)drawEntity(entity);ctx.restore();if(draft.length){ctx.strokeStyle='#f6ca7c';ctx.lineWidth=2;ctx.setLineDash([5,4]);ctx.beginPath();draft.map(screen).forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));if(ghost)ctx.lineTo(camera.x+ghost.x*camera.scale,camera.y+ghost.y*camera.scale);ctx.stroke();ctx.setLineDash([]);}
  if(ghost&&!['select','pan','point','line','polygon','river'].includes(options.tool)){ctx.strokeStyle='#f6ca7c';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(camera.x+ghost.x*camera.scale,camera.y+ghost.y*camera.scale,options.radius*camera.scale,0,Math.PI*2);ctx.stroke();}
  if(inspection)pin.show(camera.x+inspection.x*camera.scale,camera.y+inspection.y*camera.scale);else pin.hide();
  callbacks.detail(`${detailName(detailAtScale(camera.scale))} · ${(camera.scale/camera.minimum).toFixed(1)}×${tiles?.pending.size?' · refining…':''}${tiles?.error?' · '+tiles.error:''}`);
 }
 return {setInspectionPin(point){inspection=point;if(!point)pin.hide();queue();},texture:overview,setOptions(next){if(options.tool!==next.tool){draft=[];callbacks.draft(0);}options={...options,...next};queue();},setEntities(next){entities=next;selection=entities.find(e=>e.id===selection?.id)||null;queue();},select(id){selection=entities.find(e=>e.id===id)||null;queue();},invalidate(bounds){tiles?.invalidate(bounds);changed();},refresh:changed,fit,finish,state,restore(saved){if(!saved?.center||!Number.isFinite(saved.scale)||!Number.isFinite(saved.center.x)||!Number.isFinite(saved.center.y))return;camera.scale=Math.max(camera.minimum,Math.min(3072,saved.scale));camera.x=width/2-saved.center.x*camera.scale;camera.y=height/2-saved.center.y*camera.scale;changed();},dispose(){disposed=true;pin.dispose();abort.abort();observer.disconnect();tiles?.dispose();cancelAnimationFrame(frame);clearTimeout(viewportTimer);canvas.remove();}};
}
