import {useEffect,useRef,useState} from 'react';
import {RemoteSolver} from '../terrain/api.js';
export default function ProjectHub({onCreate,onOpen,onImport,busy,onDelete,active}){
 const [worlds,setWorlds]=useState([]),[error,setError]=useState(''),[filter,setFilter]=useState(''),[name,setName]=useState(''),[loading,setLoading]=useState(true);const list=useRef(null);
 async function refresh(){setLoading(true);try{const data=await RemoteSolver.savedProjects();setWorlds(data.projects);setError('');}catch(e){setError(e.message);}finally{setLoading(false);}}
 useEffect(()=>{void refresh();},[]);
 return <main className="project-hub"><section className="hub-intro"><span className="eyebrow">A place for worlds to begin</span><h1>KRIEMHILD</h1><p>Knowledge Record of Intertwined Eras,<br/>Maps, Histories, &amp; Invented Legendary Domains</p><div className="hub-create"><input aria-label="New world name" placeholder="Name your next world" value={name} onChange={e=>setName(e.target.value)} maxLength={160}/><button className="primary" disabled={busy} onClick={()=>onCreate(name.trim()||'Unnamed World')}>+ Create New World</button><button onClick={()=>list.current?.scrollIntoView({behavior:'smooth'})}>Open Existing World</button></div><div className="hub-import"><label className="button">Open World Archive<input type="file" accept=".zip" hidden disabled={busy} onChange={e=>{if(e.target.files.length)onImport([...e.target.files],false);e.target.value='';}}/></label><label className="button">Open World Project Folder<input type="file" webkitdirectory="" multiple hidden disabled={busy} onChange={e=>{if(e.target.files.length)onImport([...e.target.files],true);e.target.value='';}}/></label></div></section>
 <section className="environment-cards"><article><span>01 / NATURAL WORLD</span><h2>World Generation</h2><p>Shape continents, mountains and oceans. Explore climate, rivers and the terrain beneath them.</p><button disabled={busy} onClick={()=>onCreate(name.trim()||'Unnamed World')}>Create and generate →</button></article><article><span>02 / THE INHABITED WORLD</span><h2>World Builder</h2><p>Place settlements, draw roads and borders, and shape the landscape. Every change belongs to your world.</p><button onClick={()=>list.current?.scrollIntoView({behavior:'smooth'})}>Choose a world to build →</button></article></section>
 {active?.solver.unsaved&&<section className="working-world"><h2>Current unsaved world</h2><p>{active.project?.name||'Unnamed World'} - click Save in the top bar to keep this world and its explored terrain.</p><button disabled={busy} onClick={()=>onOpen(active.solver.worldId,'generate')}>Resume generation</button><button disabled={busy} onClick={()=>onOpen(active.solver.worldId,'build')}>Resume building</button><button className="danger" disabled={busy} onClick={()=>onDelete({id:active.solver.worldId,name:active.project?.name})}>Delete world</button></section>}
 <section className="recent-worlds" ref={list}><div className="section-heading"><div><span className="eyebrow">Your project library</span><h2>Recent Worlds</h2></div><input aria-label="Search worlds" placeholder="Search name or seed" value={filter} onChange={e=>setFilter(e.target.value)}/><button onClick={refresh} disabled={loading}>Refresh</button></div>{error&&<p role="alert" className="shell-error">{error}</p>}{loading?<p>Loading your worlds…</p>:worlds.length===0?<div className="empty-worlds">Your first world is waiting to be imagined. Create one above, or open a project archive. Worlds appear here after you click Save.</div>:<div className="world-grid">{worlds.filter(w=>`${w.name} ${w.seed}`.toLowerCase().includes(filter.toLowerCase())).map(w=><article key={w.id}><div className="world-glyph" aria-hidden="true">◈</div><h3>{w.name||'Unnamed World'}</h3><p>{w.width} × {w.height} · {w.detailTiles} explored tiles</p><p className="muted">Saved {new Date(w.updatedAt).toLocaleString()}<br/>Seed {w.seed||'—'}</p><div><button disabled={busy} onClick={()=>onOpen(w.id,'generate')}>Generation</button><button disabled={busy} onClick={()=>onOpen(w.id,'build')}>World Builder</button><button className="danger" disabled={busy} onClick={()=>onDelete(w)}>Delete world</button></div></article>)}</div>}</section></main>;
}
